AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template for Budget Sync Lambda function
Globals:
  Function:
    Timeout: 900
    Runtime: python3.9
    Handler: src.budget_sync.lambda_handler.lambda_handler
Resources:
  BudgetSyncFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.budget_sync.lambda_handler.lambda_handler
      Description: Lambda handler for processing budgets
      MemorySize: 512
      Environment:
        Variables:
          GOOGLE_APPLICATION_CREDENTIALS: config/service-account-key.json
          BIGQUERY_PROJECT_ID: budget-sync-db
          BIGQUERY_DATASET_ID: budget_data
      Events:
        BudgetSyncAPI:
          Type: Api
          Properties:
            Path: /process-budget
            Method: post
    Metadata:
      SamResourceId: BudgetSyncFunction
